// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function varsa(a) {
  var collecta = function (a) {
    var exit = 0;
    switch (a.tag | 0) {
      case 0 : 
          return /* [] */0;
      case 1 : 
          return /* :: */[
                  a[0],
                  /* [] */0
                ];
      case 2 : 
      case 3 : 
          exit = 1;
          break;
      
    }
    if (exit === 1) {
      return Pervasives.$at(collecta(a[0]), collecta(a[1]));
    }
    
  };
  var cmp = function (x, y) {
    if (Caml_obj.caml_equal(x, y)) {
      return 0;
    } else if (Caml_obj.caml_lessthan(x, y)) {
      return 1;
    } else {
      return -1;
    }
  };
  return List.sort_uniq(cmp, collecta(a));
}

function varsb(b) {
  var collectb = function (b) {
    if (b.tag === 4) {
      return Pervasives.$at(collectb(b[0]), collectb(b[1]));
    } else {
      return Pervasives.$at(varsa(b[0]), varsa(b[1]));
    }
  };
  var cmp = function (x, y) {
    if (Caml_obj.caml_equal(x, y)) {
      return 0;
    } else if (Caml_obj.caml_lessthan(x, y)) {
      return 1;
    } else {
      return -1;
    }
  };
  return List.sort_uniq(cmp, collectb(b));
}

exports.varsa = varsa;
exports.varsb = varsb;
/* No side effect */
